// ReSharper disable InconsistentNaming
// ReSharper disable GrammarMistakeInComment
// ReSharper disable CommentTypo
// ReSharper disable IdentifierTypo
namespace UE.Toolkit.Core.Types.Unreal.UE5_4_4;

[Flags]
public enum EClassFlags : uint
{
    // <summary>
    // No Flags
    // </summary>
    None = 0x00000000u,

    // <summary>
    // Class is abstract and can't be instantiated directly.
    // </summary>
    Abstract = 0x00000001u,

    // <summary>
    // Save object configuration only to Default INIs, never to local INIs. Must be combined with "Config"
    // </summary>
    DefaultConfig = 0x00000002u,

    // <summary>
    // Load object configuration at construction time.
    // </summary>
    Config = 0x00000004u,

    // <summary>
    // This object type can't be saved; null it out at save time.
    // </summary>
    Transient = 0x00000008u,

    // <summary>
    // This object type may not be available in certain context. (i.e. game runtime or in certain configuration). Optional class data is saved separately to other object types. (i.e. might use sidecar files)
    // </summary>
    Optional = 0x00000010u,

    // <summary>
    // 
    // </summary>
    MatchedSerializers = 0x00000020u,

    // <summary>
    // Indicates that the config settings for this class will be saved to Project/User*.ini (similar to "GlobalUserConfig")
    // </summary>
    ProjectUserConfig = 0x00000040u,

    // <summary>
    // Class is a native class - native interfaces will have "Native" set, but not RF_MarkAsNative
    // </summary>
    Native = 0x00000080u,

    // <summary>
    // Don't export to C++ header.
    // </summary>
    [Obsolete("No longer used in the engine.")]
    NoExport = 0x00000100u,

    // <summary>
    // Do not allow users to create in the editor.
    // </summary>
    NotPlaceable = 0x00000200u,

    // <summary>
    // Handle object configuration on a per-object basis, rather than per-class.
    // </summary>
    PerObjectConfig = 0x00000400u,

    // <summary>
    // Whether SetUpRuntimeReplicationData still needs to be called for this class
    // </summary>
    ReplicationDataIsSetUp = 0x00000800u,

    // <summary>
    // Class can be constructed from editinline New button.
    // </summary>
    EditInlineNew = 0x00001000u,

    // <summary>
    // Display properties in the editor without using categories.
    // </summary>
    CollapseCategories = 0x00002000u,

    // <summary>
    // Class is an interface
    // </summary>
    Interface = 0x00004000u,

    // <summary>
    // Config for this class is overridden in platform inis, reload when previewing platforms
    // </summary>	
    PerPlatformConfig = 0x00008000u,

    // <summary>
    // all properties and functions in this class are const and should be exported as const
    // </summary>
    Const = 0x00010000u,

    // <summary>
    // Class flag indicating objects of this class need deferred dependency loading
    // </summary>
    NeedsDeferredDependencyLoading = 0x00020000u,

    // <summary>
    // Indicates that the class was created from blueprint source material
    // </summary>
    CompiledFromBlueprint = 0x00040000u,

    // <summary>
    // Indicates that only the bare minimum bits of this class should be DLL exported/imported
    // </summary>
    MinimalAPI = 0x00080000u,

    // <summary>
    // Indicates this class must be DLL exported/imported (along with all of it's members)
    // </summary>
    RequiredAPI = 0x00100000u,

    // <summary>
    // Indicates that references to this class default to instanced. Used to be subclasses of UComponent, but now can be any UObject
    // </summary>
    DefaultToInstanced = 0x00200000u,

    // <summary>
    // Indicates that the parent token stream has been merged with ours.
    // </summary>
    TokenStreamAssembled = 0x00400000u,

    // <summary>
    // Class has component properties.
    // </summary>
    HasInstancedReference = 0x00800000u,

    // <summary>
    // Don't show this class in the editor class browser or edit inline new menus.
    // </summary>
    Hidden = 0x01000000u,

    // <summary>
    // Don't save objects of this class when serializing
    // </summary>
    Deprecated = 0x02000000u,

    // <summary>
    // Class not shown in editor drop down for class selection
    // </summary>
    HideDropDown = 0x04000000u,

    // <summary>
    // Class settings are saved to [AppData]/..../Blah.ini (as opposed to "DefaultConfig")
    // </summary>
    GlobalUserConfig = 0x08000000u,

    // <summary>
    // Class was declared directly in C++ and has no boilerplate generated by UnrealHeaderTool
    // </summary>
    Intrinsic = 0x10000000u,

    // <summary>
    // Class has already been constructed (maybe in a previous DLL version before hot-reload).
    // </summary>
    Constructed = 0x20000000u,

    // <summary>
    // Indicates that object configuration will not check against ini base/defaults when serialized
    // </summary>
    ConfigDoNotCheckDefaults = 0x40000000u,

    // <summary>
    // Class has been consigned to oblivion as part of a blueprint recompile, and a newer version currently exists.
    // </summary>
    NewerVersionExists = 0x80000000u,

    // <summary>
    // Flags to inherit from base class
    // </summary>
    Inherit = Transient | Optional | DefaultConfig | Config | PerObjectConfig | ConfigDoNotCheckDefaults | NotPlaceable | Const | HasInstancedReference |
              Deprecated | DefaultToInstanced | GlobalUserConfig | ProjectUserConfig | NeedsDeferredDependencyLoading,

    // <summary>
    // These flags will be cleared by the compiler when the class is parsed during script compilation
    // </summary>
    RecompilerClear = Inherit | Abstract | Native | Intrinsic | TokenStreamAssembled,

    // <summary>
    // These flags will be cleared by the compiler when the class is parsed during script compilation
    // </summary>
    ShouldNeverBeLoaded = Native | Optional | Intrinsic | TokenStreamAssembled,

    // <summary>
    // These flags will be inherited from the base class only for non-intrinsic classes
    // </summary>
    ScriptInherit = Inherit | EditInlineNew | CollapseCategories,

    // <summary>
    // This is used as a mask for the flags put into generated code for "compiled in" classes.
    // </summary>
    SaveInCompiledInClasses = Abstract | DefaultConfig | GlobalUserConfig | ProjectUserConfig | PerPlatformConfig | Config | Transient | Optional | Native | NotPlaceable | PerObjectConfig |
                              ConfigDoNotCheckDefaults | EditInlineNew | CollapseCategories | Interface | DefaultToInstanced | HasInstancedReference | Hidden | Deprecated |
                              HideDropDown | Intrinsic | Const | MinimalAPI | RequiredAPI | MatchedSerializers | NeedsDeferredDependencyLoading,
};